### ISSUE TITLE
How to visulaize the data (projection to a map)

### ISSUE THREAD

**Issue by JonasGreim** [JonasGreim/US-headquarter-locations#4]
Maybe with GIS (QGIS software).

I spoke with my room mate who is geoinformatician. He said it would be possible to build a dynamic map (where you can slide the year)

**Comment by robinsonlang22** [comment]
React Leaflet, Leaflet, GeoJSON

**Comment by robinsonlang22** [comment]
IDEA :

1. Show the moving of headquarters' main locations by HeatMap
2. Show two important areas which have a lot of headquarters near to each other, in  a smaller-scale-map: San Francisco area and New York area ( include other nearby locations )
